server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbuk?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true